### ISSUE TITLE
[Feature Request] Music/Sound Speed Adjustments

### ISSUE THREAD

**Issue by TSEG6** [KaboomRoads/Pale-Hollow#1]
So my idea is when you exit the biome (assuming music started playing in the biome) the music should speed back up to normal speed & if music is already playing before you enter it should slow down as you go in.
This could be a config option honestly.

But that could make it more jarring to go into the biome and then going out and it being normal.

Also some sound effects aren't affected by the slow down like the creeper priming sound effect for example.

Hopefully this is understandable lol

**Comment by KaboomRoads** [comment]
small note: Minecraft clamps sound pitch to 0.5-2.0 and the creeper sound is already by default played at 0.5 pitch so it doesn't change
